### ISSUE TITLE
implement cli-terraform

### ISSUE THREAD

**Issue by ynohat** [akamai/akamai-docker#14]
cc @javiergarza @lukaszczerpak @edglynes

(@edglynes there is also a repo with cli-terraform-gtm; is that an older one that will be retired, or should we also consider it?)

The initial release of the Docker containers will not contain this CLI but we should be able to integrate it very quickly.

Current proposal in the discussion on #13 is to create a new variant containing terraform and the CLI.

I am unsure about this; since the CLI does not depend on terraform, I wonder if it doesn't make more sense to use exactly the same formalism as the other variants: one variant per CLI.

My reasoning:

* Cost of downloading two variants is low
* I still think it unlikely that customers will use the terraform variant for every day work, the CLI would probably be used to bootstrap Akamai configurations within their existing setup in most cases
* Consistency

**Comment by edglynes** [comment]
cli-terraform-gtm has been deprecated with the release of cli-terraform. It can be removed from the Docker container at your earlier convenience.

I am currently working on a cli-dns update and will be updating the cli package inventory in the next weeks to month as well… I could remove then.

Ed

**Comment by javiergarza** [comment]
I think it will be better to have a separate docker package for the Terraform CLI

**Comment by lukaszczerpak** [comment]
Originally I was leaning towards a single variant with terraform+provider+terraform-cli, but reasons provided by @ynohat are valid and it makes sense to create a separate variant.
