### ISSUE TITLE
monthly builds not on first of month?

### ISSUE THREAD

**Issue by ynohat** [akamai/akamai-docker#15]
I have a concern that monthly builds don't take place on the first of the month; this is a small issue, but it would be easier if we could fix this.

**Comment by javiergarza** [comment]
I checked the Travis logs and I can see the monthly build happened 8 days ago. 

Seems Travis monthly builds start counting from the date it is configured which in our case was the 17th, so the next monthly build will happen on July 17, 2020.

Ideally we should not need a monthly build if we deploy automatically whenever a new CLI package is updated. Let's look into that...
