### ISSUE TITLE
File mounting description incorrect on `readme.md`

### ISSUE THREAD

**Issue by v0d** [akamai/akamai-docker#18]
`README.md` states in the **General Usage** Section:
- Expects `.edgerc` file at `/root/.edgerc` (See Authentication)

actually the command
`docker run --rm -v $HOME/.edgerc:/root/.edgerc:ro akamai/purge akamai purge invalidate --cpcode 123456`
is expecting `.edgerc` at  `$HOME/.edgerc` and mounting it to `/root/.edgerc`

**Comment by ynohat** [comment]
Thank you @v0d !
I will clarify that those points explain the behavior of the container rather than the example itself.

**Comment by javiergarza** [comment]
@v0d FYI we just updated the README to clarify that. Thanks for the feedback!
