### ISSUE TITLE
Missing auth in akamai/shell

### ISSUE THREAD

**Issue by mhainke** [akamai/akamai-docker#20]
For verification of the sections in .edgerc it's helpful to check them with "akamai auth verify" but I'm missing the module "auth" in the akamai/shell - image. 

Do you have it on your agenda to add it?

**Comment by lukaszczerpak** [comment]
hi @mhainke, `auth` CLI module is deprecated and thus not included in the image. We will add a replacement once it's ready. The decision to remove it was mainly dictated by unreliable/incomplete information provided by this CLI. As a result it could have been confusing as not giving the right information.

**Comment by mhainke** [comment]
Thank you for clarification!

**Comment by javiergarza** [comment]
@mhainke FYI https://github.com/akamai/cli-auth has been archived and includes a note indicating the reason.
