### ISSUE TITLE
unable to pull akamai/base

### ISSUE THREAD

**Issue by anirban1c** [akamai/akamai-docker#26]
Hello, 
is this repo still working ? 

anirban@chimera-2:/mnt/sde1/apps/oss/akamai-docker$ docker pull akamai/base
Using default tag: latest
Error response from daemon: pull access denied for akamai/base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
anirban@chimera-2:/mnt/sde1/apps/oss/akamai-docker$

thanks, 
-anirban

**Comment by javiergarza** [comment]
Hi Anirban, 

The akamai/base image is an intermediary image that is used as base for all the repos but it does nothing other than provide a basic shell by itself. 

What are you trying to do?

**Comment by anirban1c** [comment]
was trying to get build akamai cli with all the plugins, got a working one finally, so all good
https://hub.docker.com/repository/docker/anirban1c/akamai-cli-hub

thanks,
-anirban

**Comment by javiergarza** [comment]
Hi Anirban,

We already have a docker image for that on https://hub.docker.com/r/akamai/shell

Hope this helps!

Best regards,

Javier
