### ISSUE TITLE
Docker image for the EAA CLI

### ISSUE THREAD

**Issue by bitonio** [akamai/akamai-docker#31]
Hello Akamai Developer team,

Would it be possible to get a new docker image with the EAA CLI module in it?

Thanks

**Comment by lukasz-czerpak-maersk** [comment]
Hello Antoine,

Many thanks for reaching out. We're looking into it and will get back to you soon.

Best regards,
Łukasz Czerpak

**Comment by lukaszczerpak** [comment]
Hello Antoine,

Many thanks for reaching out. We're looking into it and will get back to you soon.

Best regards,
Łukasz Czerpak

**Comment by lukaszczerpak** [comment]
Hello @bitonio

We've added cli-eaa to the dev branch in order to test it. You can pull it as follows:

```
docker pull akamai/eaa:dev
```

Would you be able to test it on your side and confirm it's working as expected?

Thanks!

**Comment by bitonio** [comment]
Did a basic smoke-test, all good for me!
Thank you for the quick turn around @lukaszczerpak

**Comment by lukaszczerpak** [comment]
Many thanks @bitonio ! We just released the new cli-eaa image in prod. Enjoy! :)
