### ISSUE TITLE
Add cli-cloudlets to the image

### ISSUE THREAD

**Issue by lukaszczerpak** [akamai/akamai-docker#8]
We need to add cli-cloudlets to the Dockerfile. It's not listed in `packages-list.json` on DAC site therefore must be added explicitly.

**Comment by javiergarza** [comment]
I can take care of this as is part of my role

On Apr 23, 2020, at 08:53, Łukasz Czerpak <notifications@github.com> wrote:

﻿

We need to add cli-cloudlets to the Dockerfile. It's not listed in packages-list.json on DAC site therefore must be added explicitly.

**Comment by javiergarza** [comment]
The cloudlets CLI is returned by packages-list.json now and I confirm the latest akamai-docker build contains it
