### ISSUE TITLE
container with support of NetStorage

### ISSUE THREAD

**Issue by mguentge** [akamai/akamai-docker#82]
Is there any practice to use Docker with NetStorage?
Can you extend the repository of containers with a container of NetStorage? NetStorage CLI?

**Comment by Slonimskaia** [comment]
Hello @mguentge ,

Thank You for reporting this issue. We will prioritize this request and come back to you soon 

Best Regards,
Tatiana Slonimskaia

**Comment by mguentge** [comment]
The customer started to replicate by rclone now. It does no more have relevance.

Thank you,
Marc

From: Tatiana Slonimskaia ***@***.***>
Reply-To: akamai/akamai-docker ***@***.***>
Date: Friday, January 20, 2023 at 3:12 PM
To: akamai/akamai-docker ***@***.***>
Cc: Marc Guentgen ***@***.***>, Mention ***@***.***>
Subject: Re: [akamai/akamai-docker] container with support of NetStorage (Issue #82)


Hello @mguentge<https://urldefense.com/v3/__https:/github.com/mguentge__;!!GjvTz_vk!S8dt2ALjWlLfZspsRP9lC1IXLCjk-rM7nnZ1AaK7XVEG8Zt9rxwQ7NUTWnJ2PJmyJw67kaiINzv8Wfo-kEhvmlI$> ,

Thank You for reporting this issue. We will prioritize this request and come back to you soon

Best Regards,
Tatiana Slonimskaia

**Comment by lkowalsk-akamai-com** [comment]
We will track this internally, but no commitments whether this container will be added
